var a = layer_get_id("background");
var b = layer_get_id("backgrounds_1");
var c = layer_get_id("backgrounds_2");
var d = layer_get_id("backgrounds_3");
var e = layer_get_id("backgrounds_4");
var f = layer_get_id("backgrounds_5");
var g = layer_get_id("backgrounds_6");
var h = layer_get_id("backgrounds_7");
var j = layer_get_id("backgrounds_8");
var k = layer_get_id("backgrounds_9");
var l = layer_get_id("backgrounds_10");
var m = layer_get_id("backgrounds_11");
var n = layer_get_id("backgrounds_12");
var o = layer_get_id("backgrounds_13");
var p = layer_get_id("backgrounds_14");
var q = layer_get_id("backgrounds_15");
var r = layer_get_id("backgrounds_16");
var s = layer_get_id("backgrounds_17");
var t = layer_get_id("backgrounds_18");
var u = layer_get_id("background_19");
var v = layer_get_id("background_20");
var w = layer_get_id("background_21");

layer_x( a,lerp(0,camera_get_view_x(view_camera[0]),0.86) );
layer_x( b,lerp(0,camera_get_view_x(view_camera[0]),0.88) );
layer_x( c,lerp(0,camera_get_view_x(view_camera[0]),0.90) );
layer_x( d,lerp(0,camera_get_view_x(view_camera[0]),0.85) );
layer_x( e,lerp(0,camera_get_view_x(view_camera[0]),0.80) );
layer_x( f,lerp(0,camera_get_view_x(view_camera[0]),0.55) );
layer_x( g,lerp(0,camera_get_view_x(view_camera[0]),0.50) );
layer_x( h,lerp(0,camera_get_view_x(view_camera[0]),0.45) );
layer_x( j,lerp(0,camera_get_view_x(view_camera[0]),0.40) );
layer_x( k,lerp(0,camera_get_view_x(view_camera[0]),0.35) );
layer_x( l,lerp(0,camera_get_view_x(view_camera[0]),0.30) );
layer_x( m,lerp(0,camera_get_view_x(view_camera[0]),0.26) );
layer_x( n,lerp(0,camera_get_view_x(view_camera[0]),0.22) );
layer_x( o,lerp(0,camera_get_view_x(view_camera[0]),0.18) );
layer_x( p,lerp(0,camera_get_view_x(view_camera[0]),0.16) );
layer_x( q,lerp(0,camera_get_view_x(view_camera[0]),0.14) );
layer_x( r,lerp(0,camera_get_view_x(view_camera[0]),0.10) );
layer_x( s,lerp(0,camera_get_view_x(view_camera[0]),0.15) );
layer_x( t,lerp(0,camera_get_view_x(view_camera[0]),0.25) );
layer_x( u,lerp(0,camera_get_view_x(view_camera[0]),-0.60) );
layer_x( v,lerp(0,camera_get_view_x(view_camera[0]),0.15) );
layer_x( w,lerp(0,camera_get_view_x(view_camera[0]),0.10) );